# Generated by Django 5.2.4 on 2026-06-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_update_pin_to_4_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guilder',
            name='membership_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Distant', 'Distant')], default='Active', max_length=20),
        ),
    ]
