# Generated by Django 5.2.4 on 2026-06-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_guilder_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregation',
            name='initials',
            field=models.CharField(blank=True, default='', help_text='Short initials used for member ID generation (e.g. AE)', max_length=10),
        ),
        migrations.AddField(
            model_name='guilder',
            name='member_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='guilder',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='member_pictures/'),
        ),
    ]
