# Generated by Django 5.2.4 on 2026-08-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_congregation_initials_guilder_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guilder',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
