# Generated by Django 5.2.4 on 2026-08-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_make_date_of_birth_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guilder',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
