# Generated by Django 5.2.4 on 2026-08-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_phone_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilder',
            name='member_level',
            field=models.CharField(choices=[('local', 'Local'), ('district', 'District')], default='local', help_text='Whether this member was added from a local or district dashboard', max_length=10),
        ),
    ]
