# Generated by Django 5.2.4 on 2026-08-21 08:49

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_member_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Full snapshot of congregations, members and attendance')),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('pre_clear', 'Pre-Clear Safety')], default='manual', max_length=20)),
                ('members_count', models.PositiveIntegerField(default=0)),
                ('attendance_count', models.PositiveIntegerField(default=0)),
                ('congregations_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
