# Generated by Django 5.2.4 on 2026-08-22 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_databackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregation',
            name='leader_phone',
            field=models.CharField(blank=True, default='', help_text="Leader's phone for SMS reminders (e.g. 0241234567)", max_length=20),
        ),
        migrations.CreateModel(
            name='SundayReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.congregation')),
            ],
            options={
                'unique_together': {('congregation', 'sent_date')},
            },
        ),
    ]
