# Generated by Django 5.2.4 on 2026-08-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_websitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilder',
            name='member_type',
            field=models.CharField(choices=[('existing', 'Existing'), ('new', 'New')], default='existing', help_text='Whether this is an existing (old) or new member', max_length=10),
        ),
        migrations.AddField(
            model_name='guilder',
            name='purpose_of_joining',
            field=models.TextField(blank=True, default='', help_text='What brought you or purpose of joining', null=True),
        ),
        migrations.AlterField(
            model_name='guilder',
            name='membership_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Distant', 'Distant'), ('New', 'New')], default='Active', max_length=20),
        ),
    ]
