# Generated by Django 5.2.4 on 2026-08-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_member_type_and_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilder',
            name='original_new_member_id',
            field=models.CharField(blank=True, help_text='Preserved YPG-NM-... ID when a new member is promoted to existing', max_length=30, null=True),
        ),
    ]
