# Generated by Django 5.2.4 on 2026-08-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_original_new_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guilder',
            name='original_new_member_id',
            field=models.CharField(blank=True, help_text='Preserved congregation-scoped NM ID when a new member is promoted to existing', max_length=30, null=True),
        ),
    ]
