# Generated by Django 5.2.4 on 2026-09-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_custom_and_scheduled_sms_logs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guilder',
            unique_together={('first_name', 'last_name', 'congregation')},
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('local', 'Local Executive'), ('district', 'District Executive'), ('both', 'Both Local & District Executive')], help_text='Level of this executive role (Local, District, or Both)', max_length=20)),
                ('local_position', models.CharField(blank=True, choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('assistant_secretary', 'Assistant Secretary'), ('financial_secretary', 'Financial Secretary'), ('treasurer', 'Treasurer'), ('organizer', 'Organizer'), ('evangelism_coordinator', 'Evangelism Coordinator')], help_text='Local executive position if applicable', max_length=50, null=True)),
                ('district_position', models.CharField(blank=True, choices=[('president', 'President'), ('presidents_rep', "President's Rep"), ('secretary', 'Secretary'), ('assistant_secretary', 'Assistant Secretary'), ('financial_secretary', 'Financial Secretary'), ('treasurer', 'Treasurer'), ('organizer', 'Organizer'), ('evangelism_coordinator', 'Evangelism Coordinator')], help_text='District executive position if applicable', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this executive role is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('congregation', models.ForeignKey(help_text='Congregation where this executive role is held', on_delete=django.db.models.deletion.CASCADE, to='core.congregation')),
                ('guilder', models.ForeignKey(help_text='The member who holds this executive role', on_delete=django.db.models.deletion.CASCADE, related_name='executive_roles', to='core.guilder')),
            ],
            options={
                'ordering': ['guilder__first_name', 'guilder__last_name'],
                'indexes': [models.Index(fields=['level', 'is_active'], name='core_execut_level_9d78f2_idx'), models.Index(fields=['congregation', 'level'], name='core_execut_congreg_e3e034_idx'), models.Index(fields=['guilder', 'is_active'], name='core_execut_guilder_38336f_idx')],
            },
        ),
    ]
